"""
Demo / smoke-test script.

Generates a synthetic bank statement image in memory (no real PDF needed),
runs the full extraction pipeline, and prints results.

Run:
    python -m statement_extractor.demo
"""
from __future__ import annotations

import json
import os
import sys
import tempfile

import cv2
import numpy as np


# ---------------------------------------------------------------------------
# Synthetic statement generator
# ---------------------------------------------------------------------------

def _make_synthetic_statement() -> str:
    """
    Draw a minimal 3-column bank statement table on a white canvas and
    save it as a PNG.  Returns the file path.
    """
    W, H = 900, 700
    img = np.ones((H, W, 3), dtype=np.uint8) * 255  # white background

    font      = cv2.FONT_HERSHEY_SIMPLEX
    font_bold = cv2.FONT_HERSHEY_DUPLEX
    grey      = (80, 80, 80)
    black     = (0, 0, 0)

    # Title
    cv2.putText(img, "ACME BANK - Account Statement", (60, 45), font_bold, 0.9, black, 2, cv2.LINE_AA)
    cv2.putText(img, "Account No: 1234567890   Period: 01-May-2024 to 31-May-2024",
                (60, 80), font, 0.55, grey, 1, cv2.LINE_AA)

    # Horizontal divider
    cv2.line(img, (40, 95), (860, 95), (150, 150, 150), 1)

    # ── Header row ──
    headers = ["Date", "Description", "Withdrawal (Dr)", "Deposit (Cr)", "Balance"]
    col_x   = [50, 160, 420, 565, 710]
    cv2.putText(img, headers[0], (col_x[0], 125), font_bold, 0.58, black, 1, cv2.LINE_AA)
    cv2.putText(img, headers[1], (col_x[1], 125), font_bold, 0.58, black, 1, cv2.LINE_AA)
    cv2.putText(img, headers[2], (col_x[2], 125), font_bold, 0.55, black, 1, cv2.LINE_AA)
    cv2.putText(img, headers[3], (col_x[3], 125), font_bold, 0.55, black, 1, cv2.LINE_AA)
    cv2.putText(img, headers[4], (col_x[4], 125), font_bold, 0.58, black, 1, cv2.LINE_AA)
    cv2.line(img, (40, 135), (860, 135), (180, 180, 180), 1)

    # ── Transaction rows ──
    rows = [
        ("01/05/2024", "Opening Balance",                "",           "",          "50,000.00"),
        ("03/05/2024", "UPI-PHONEPE-Grocery Store",      "1,200.00",   "",          "48,800.00"),
        ("05/05/2024", "NEFT-SALARY-ACME CORP LTD",      "",           "75,000.00", "1,23,800.00"),
        ("07/05/2024", "ATM Withdrawal SBI ATM",         "5,000.00",   "",          "1,18,800.00"),
        ("10/05/2024", "IMPS-9876543210-Rent Payment",   "25,000.00",  "",          "93,800.00"),
        ("12/05/2024", "Interest Credit Q1",             "",           "342.50",    "94,142.50"),
        ("15/05/2024", "UPI-AMAZON-Online Shopping",     "3,499.00",   "",          "90,643.50"),
        ("18/05/2024", "NEFT-FREELANCE-Rajesh Kumar",    "",           "12,000.00", "1,02,643.50"),
        ("22/05/2024", "Electricity Bill BESCOM",        "2,140.00",   "",          "1,00,503.50"),
        ("28/05/2024", "Bank Charges + GST",             "295.00",     "",          "1,00,208.50"),
    ]

    y_start = 160
    row_h   = 48

    for i, (date, desc, dr, cr, bal) in enumerate(rows):
        y = y_start + i * row_h
        shade = (245, 245, 245) if i % 2 == 0 else (255, 255, 255)
        cv2.rectangle(img, (40, y - 18), (860, y + 22), shade, -1)

        # Multiline desc: split on "-" after 26 chars for demo
        desc_line1 = desc[:28]
        desc_line2 = desc[28:] if len(desc) > 28 else ""

        cv2.putText(img, date,       (col_x[0], y), font, 0.50, black, 1, cv2.LINE_AA)
        cv2.putText(img, desc_line1, (col_x[1], y), font, 0.48, grey,  1, cv2.LINE_AA)
        if desc_line2:
            cv2.putText(img, desc_line2, (col_x[1], y + 16), font, 0.45, grey, 1, cv2.LINE_AA)
        cv2.putText(img, dr,         (col_x[2], y), font, 0.50, (0, 0, 180),  1, cv2.LINE_AA)
        cv2.putText(img, cr,         (col_x[3], y), font, 0.50, (0, 130, 0),  1, cv2.LINE_AA)
        cv2.putText(img, bal,        (col_x[4], y), font, 0.50, black,         1, cv2.LINE_AA)

    # Footer
    cv2.line(img, (40, H - 60), (860, H - 60), (180, 180, 180), 1)
    cv2.putText(img, "Closing Balance: INR 1,00,208.50",
                (60, H - 35), font, 0.55, black, 1, cv2.LINE_AA)
    cv2.putText(img, "Generated by ACME Bank  |  This is a system-generated statement.",
                (60, H - 15), font, 0.40, grey, 1, cv2.LINE_AA)

    # Save to temp file
    tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False, prefix="acme_stmt_")
    cv2.imwrite(tmp.name, img)
    tmp.close()
    return tmp.name


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    print("=" * 65)
    print("  Statement Extractor — Synthetic Demo")
    print("=" * 65)

    # Generate synthetic statement
    img_path = _make_synthetic_statement()
    print(f"\n[1/4] Synthetic statement image created: {img_path}")

    # Import here to allow the synthetic image to be created even if deps missing
    try:
        from statement_extractor import StatementExtractor
        from statement_extractor.config import ExtractorConfig, OCRConfig
    except ImportError as exc:
        print(f"\n[ERROR] Import failed: {exc}")
        print("Run:  pip install paddlepaddle paddleocr opencv-python-headless pymupdf scikit-learn rapidfuzz")
        sys.exit(1)

    config = ExtractorConfig(
        ocr=OCRConfig(dpi=200, use_gpu=False),
        debug=True,
        debug_output_dir="output/debug_output",
    )

    print("[2/4] Initialising StatementExtractor …")
    extractor = StatementExtractor(config)

    print("[3/4] Running extraction pipeline …")
    result = extractor.extract(img_path)

    print(f"[4/4] Done — {len(result.transactions)} transaction(s) extracted "
          f"from {result.total_pages} page(s)\n")

    if result.extraction_warnings:
        for w in result.extraction_warnings:
            print(f"  [WARN] {w}")

    print(f"\nColumn mapping: {result.column_mapping}\n")

    # Print transactions table
    print(f"{'DATE':<14} {'DESCRIPTION':<34} {'DEBIT':>12} {'CREDIT':>12} {'BALANCE':>14}  STATUS")
    print("-" * 100)
    for t in result.transactions:
        print(
            f"{str(t.txn_date):<14} "
            f"{str(t.description or '')[:33]:<34} "
            f"{str(t.debit or ''):>12} "
            f"{str(t.credit or ''):>12} "
            f"{str(t.balance or ''):>14}  "
            f"{t.validation_status.value}"
        )

    # Save outputs
    extractor.save_json(result, "output/demo_output.json")
    extractor.save_csv(result, "output/demo_output.csv")
    print("\nOutputs saved:")
    print("  → output/demo_output.json")
    print("  → output/demo_output.csv")
    print("  → output/debug_output/page_000_debug.png")

    # Cleanup temp image
    try:
        os.unlink(img_path)
    except OSError:
        pass

    print("\nDemo complete.\n")


if __name__ == "__main__":
    main()
